### ISSUE TITLE
番剧名中含数字时直接翻车。。。

### ISSUE THREAD

**Issue by noname0emmm** [Nriver/Episode-ReName#13]
86-不存在的战区-，昨天做的时候运行后就剩一集了，后来是把文件名里的86删掉才正常的（估计不太好解决）

**Comment by Nriver** [comment]
把名字发来看看

**Comment by noname0emmm** [comment]
[AI-Raws] 86 #01 アンダーテイカー (BD HEVC 1920x1080 yuv444p10le FLAC)[D87151C0].mkv

**Comment by Nriver** [comment]
这个已经在几天前兼容了，重复issue https://github.com/Nriver/Episode-ReName/issues/12
更新到最新版本即可

**Comment by Nriver** [comment]
增加了新功能, 把剧集名字写进`ignore`文件里就行了.
https://github.com/Nriver/Episode-ReName/releases/tag/v1.2.1
