### ISSUE TITLE
[命名格式兼容]

### ISSUE THREAD

**Issue by Fantuan-cell** [Nriver/Episode-ReName#14]
**你想要兼容什么类型的文件命名，请把完整的文件名写出来**
1. [DMG][Bakuman2][25_END][AVC_AAC][720P].sc.ass
2. [DMG][Bakuman2][25_END][AVC_AAC][720P].tc.ass
此文件在最后一集的集数上加上了END,程序无法识别,重命名,请求兼容

**Comment by Nriver** [comment]
已经在最新版本兼容，请更新
