### ISSUE TITLE
建议新增重命名功能

### ISSUE THREAD

**Issue by Fantuan-cell** [Nriver/Episode-ReName#15]
GmTeam发布的凡人修仙传是按篇章名发布的，并不是按照官方的命名格式。 官方的命名格式是第1集到第64集。而GmTeam发布的凡人修仙传是每一个篇章从新命名，如[凡人修仙传 再别天南 ][01], [凡人修仙传 初入星海 ][01]，这样会导致重命名覆盖。能否新增这个重命名的集数在原来的集数上增加的功能
附上链接 http://share.dmhy.org/topics/view/610752_GM-Team_Fan_Ren_Xiu_Xian_Zhuan_2022_01-04_AVC_GB_1080P.html

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Nriver** [comment]
已有功能，请参考说明 https://github.com/Nriver/Episode-ReName#多季番剧tmdb集数适配

**Comment by Fantuan-cell** [comment]
凡人修仙传只有一季，tmdb上也是只有一季。我是说Gm-team发布的资源将这一季的不同篇章分成了单独的集数。这样就导致每一个篇章都是从S01E01开始的，会覆盖掉以前的文件。你已有功能不是说匹配多季吗，需求不一样，现在是需要再之前的篇章上剧集数加一，不让他在每个篇章从1开始命名。

**Comment by Nriver** [comment]
请换个思路，用更具体的关键字过滤每个篇章，每个篇章设置不同的修正数值。不同篇章从1开始计算集数和多季资源每季从1开始计数没有本质区别。

**Comment by Nriver** [comment]
请换个思路，用更具体的关键字过滤每个篇章，每个篇章设置不同的修正数值。不同篇章从1开始计算集数和多季资源每季从1开始计数没有本质区别。

**Comment by Nriver** [comment]
参考 https://github.com/Nriver/qb-rss-manager 每一季或者篇章，对应一条订阅，每条订阅单独设置修正
