### ISSUE TITLE
不取消qbittorrent做种是否影响该程序使用

### ISSUE THREAD

**Issue by wjw054509** [Nriver/Episode-ReName#16]
因为部分下载的电影需要做种，下载的动漫需要使用该程序进行重命名，如果不取消qbittorrent做种是否影响该程序使用

**Comment by Nriver** [comment]
影响。就好比你无法在文件管理器里对一个已经打开的word文档重命名。

**Comment by wjw054509** [comment]
> 影响。就好比你无法在文件管理器里对一个已经打开的word文档重命名。

感谢解答，再咨询下，这个path后面是否支持添加多个文件夹路径

**Comment by Nriver** [comment]
> > 影响。就好比你无法在文件管理器里对一个已经打开的word文档重命名。
> 
> 感谢解答，再咨询下，这个path后面是否支持添加多个文件夹路径

不支持。一个次命令只能修改一个路径下的文件。

**Comment by wmbin** [comment]
其实通过qb的web api接口先对种子进行暂停，然后重命名后，在启动起来
