### ISSUE TITLE
请问每集动画我想保留多个版本，该如何处理

### ISSUE THREAD

**Issue by ikemenrourou** [Nriver/Episode-ReName#19]
如图，追新番的时候每集共有3个版本的文件，我想在大大软件处理后的基础上保留括号里的文字，做成SXXEXX（XXXXX）的格式，我该怎么做？
（不好意思，小白真滴看不懂py，试着解决问题未果，求大大救救孩子吧TAT）
![1111](https://user-images.githubusercontent.com/34646702/205736466-1b016c20-1f34-4792-bfc2-cd393e8a99de.png)

**Comment by Nriver** [comment]
不支持这样的命名。要保留多版本请手动处理吧。

**Comment by ikemenrourou** [comment]
好吧，感谢回答TAT，还是选一个版本保留吧
