### ISSUE TITLE
[BUG反馈] 群晖套件版qbittorrent下载后不会自动重命名

### ISSUE THREAD

**Issue by lijiazhiren** [Nriver/Episode-ReName#20]
**问题描述**
请简要描述你遇到的问题.
下载后不会自动重命名
**复现步骤**
1. 在什么环境运行了什么命令    
2. 群晖套件版qbittorrent v4.4.5.10
3. 
4. 报错信息
3个步骤都已经做好 
在qbittorrent里加上 
/usr/local/bin/python3 /var/services/homes/admin/EpisodeReName.py --path "%D" --delay 15 --overwrite 1 
这段没有反应

在进入群晖ssh执行 
/usr/local/bin/python3 /var/services/homes/admin/EpisodeReName.py /volume1/QBDow
是可以重命名的

root@ZHONGXIN:/volume1/QBDow# /usr/local/bin/python3 /var/services/homes/admin/EpisodeReName.py /volume1/QBDow
| INFO     | ('target_path', '/volume1/QBDow')
| INFO     | 文件夹处理
| INFO     | ('解析文件', '/volume1/QBDow/不道德公会/Season 1/dfsdfsdf-02.mp4')
| INFO     | 括号内未识别, 开始寻找括号外内容
| INFO     | 找末尾是数字的子字符串
| INFO     | <re.Match object; span=(0, 2), match='02'>
| INFO     | ('01', '02')
| INFO     | S01E02.mp4
| INFO     | ('解析文件', '/volume1/QBDow/不道德公会/Season 1/dsfsdfds-06.mp4')
| INFO     | 括号内未识别, 开始寻找括号外内容
| INFO     | 找末尾是数字的子字符串
| INFO     | <re.Match object; span=(0, 2), match='06'>
| INFO     | ('01', '06')
| INFO     | S01E06.mp4
| INFO     | ('file_lists', [['/volume1/QBDow/不道德公会/Season 1/dfsdfsdf-02.mp4', '/volume1/QBDow/不道德公会/Season 1/S01E02.mp4'], ['/volume1/QBDow/不道德公会/Season 1/dsfsdfds-06.mp4', '/volume1/QBDow/不道德公会/Season 1/S01E06.mp4']])
| INFO     | 运行完毕
root@ZHONGXIN:/volume1/QBDow# 

**截图**
如果有截图，请附上

**Comment by Nriver** [comment]
qb下载完了等15秒才会重命名。

**Comment by lijiazhiren** [comment]
我开始反馈到现在也有几个小时了 依然没有重命名

**Comment by Nriver** [comment]
应该是qb有哪里没配置好吧, 配置的路径, 符号, 权限, 都有有可能.
