### ISSUE TITLE
[命名格式兼容]希望命名可以兼容清晰度

### ISSUE THREAD

**Issue by Chenxi-Chris** [Nriver/Episode-ReName#21]
**你想要兼容什么类型的文件命名，请把完整的文件名写出来**
1. wednesday.s01e03.2160p.web.h265-donuts.mkv
2. Wednesday.S01E03.1080p.WEBRip.x265-RARBG.mp4

希望命令增加参数以支持清晰度命名

期望结果是这样:
1. S01E03 - 2160p.mkv
2. S01E03 - 1080p.mp4

感谢

**Comment by Nriver** [comment]
新版本增加了分辨率解析 https://github.com/Nriver/Episode-ReName/releases/tag/v1.2.0

**Comment by Chenxi-Chris** [comment]
> 新版本增加了分辨率解析 https://github.com/Nriver/Episode-ReName/releases/tag/v1.2.0

刚刚升级尝试了一下，很好用，感谢作者 @Nriver ！
