### ISSUE TITLE
番剧名字带年份的，把年份识别成集数了

### ISSUE THREAD

**Issue by kurokud** [Nriver/Episode-ReName#22]
番剧名字带年份的，把年份识别成集数了

| INFO     | ('解析文件', '/Downloads/动画/新番/福星小子/Season01/[Lilith-Raws] Urusei Yatsura (2022) - 08 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4')
| INFO     | ('01', '2022')
| INFO     | S01E2022.mp4

**Comment by Nriver** [comment]
增加了新功能, 把剧集名字写进`ignore`文件里就行了.
https://github.com/Nriver/Episode-ReName/releases/tag/v1.2.1
