### ISSUE TITLE
[BUG反馈] UnRaid Docker 无法重命名

### ISSUE THREAD

**Issue by aaaol** [Nriver/Episode-ReName#24]
**问题描述**
请简要描述你遇到的问题.
版本 linuxserver/qbittorrent
重群晖转移到 UnRaid 配置文件都是一样的 脚本也丢进去了,也试过放进下载目录都无法修改
**复现步骤**
1. 在什么环境运行了什么命令
2. 报错信息

**截图**
如果有截图，请附上

**Comment by aaaol** [comment]
问题解决 替换老版本可以重命名 
2023.02.27下载的版本不行
2022.08.17 下载的版本可用

**Comment by Nriver** [comment]
有没有详细的日志信息？
