### ISSUE TITLE
希望all.txt能加入负数支持

### ISSUE THREAD

**Issue by verygoodlee** [Nriver/Episode-ReName#25]
有些一季分割放松的后半段，字幕组标的第1集，TMDB是累计的13集，
我测试目前all.txt只支持正数，无法兼容这种情况，
简单加入负数支持就行了`1 - (-12) = 13`

**Comment by Nriver** [comment]
修复了负数支持，试试最新版 https://github.com/Nriver/Episode-ReName/releases/tag/v1.2.2
