### ISSUE TITLE
希望all.txt能加入加集支持

### ISSUE THREAD

**Issue by wmbin** [Nriver/Episode-ReName#26]
一些番在tmdb上第二季开始集数是从第一季集数基础上加的,但是正常的rss订阅获取是从S02E01开始的
比如：https://www.themoviedb.org/tv/107371?language=zh-CN

**Comment by Nriver** [comment]
没看懂你要实现什么效果

**Comment by wmbin** [comment]
@Nriver 和现在功能相反，之前是减，现在想实现 加 的效果
比如第一季26集，在tmdb里第二季是从第27集开始的，而种子是第二季第1集开始
自动重命名想把 S02E01改成S02E27

**Comment by Nriver** [comment]
更新了功能说明，方便后面的用户参考。

**Comment by wmbin** [comment]
@Nriver 可以了，谢谢大佬
然后就是第二个问题：
可以实现只对最新文件进行识别重命名操作吗
发现识别命名的时候会把当前目录下的所有符合规则的文件都进行操作，即使之前已经操作重命名后但是经过tmm刮削后文件名已经有了改变也会进行操作，

**Comment by Nriver** [comment]
这个，没有办法区分哪个文件是新的，哪个是旧的。我都不用tmm改剧集的名字的。

**Comment by wmbin** [comment]
@Nriver 好的
第三个问题：
关于识别处理使用大写中文的数字命名的集数，未来会支持吗
现在一些网盘资源集数不是小写阿拉伯数字，而是大写的中文数字

**Comment by Nriver** [comment]
中文数字不会支持，中文命名太杂，不好解析
