### ISSUE TITLE
[BUG反馈]all.txt文件处理

### ISSUE THREAD

**Issue by wmbin** [Nriver/Episode-ReName#27]
**问题描述**
all.txt在处理增加删除集数时候，将之前的文件也一起处理了

**复现步骤**
1. 在什么环境运行了什么命令
2. 报错信息

**截图**
| INFO     | 文件夹处理
| INFO     | ('解析文件', '/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E53 - 第 53 集.mp4')
| INFO     | ('02', '53')
| INFO     | S02E105.mp4
| INFO     | ('解析文件', '/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E54 - 第 54 集.mp4')
| INFO     | ('02', '54')
| INFO     | S02E106.mp4
| INFO     | ('解析文件', '/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E11 - 第 11 集.mp4')
| INFO     | ('02', '11')
| INFO     | S02E63.mp4
| INFO     | ('file_lists', [['/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E53 - 第 53 集.mp4', '/volume5/迅雷/测试项目/Season 2/S02E105.mp4'], ['/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E54 - 第 54 集.mp4', '/volume5/迅雷/测试项目/Season 2/S02E106.mp4'], ['/volume5/迅雷/测试项目/Season 2/一念永恒 - S02E11 - 第 11 集.mp4', '/volume5/迅雷/测试项目/Season 2/S02E63.mp4']])
| INFO     | 运行完毕

**Comment by Nriver** [comment]
功能是正常的，不是标准命名的都会进行重命名操作

**Comment by wmbin** [comment]
@Nriver 大概懂识别原理了，标准命不是 S{season}E{ep}的文件都会加入重命名列表，只要名称有多余的字符都算做新文件，也需要加入重命名列表

**Comment by Nriver** [comment]
是的，只有 S{season}E{ep} 的文件不会处理

**Comment by Nriver** [comment]
重命名工具传入的是单个文件就可以只重命名单个文件。qb下载完之后传的是目录，这样就会把整个目录的文件都重命名。有办法把下了哪个文件传出来吗？

**Comment by wmbin** [comment]
正常的rss订阅, 每个任务的Torrent 就是一个视频，而“%N：Torrent 名称” 就是视频的名称。
“重命名工具传入的是单个文件就可以只重命名单个文件”
就可以通过拼接的方法  %D 保存地址+%N 视频名称，传递给重命名工具了
