### ISSUE TITLE
[BUG反馈]在命令行中存在输出，但是文件并没有被重命名

### ISSUE THREAD

**Issue by YumiGoo** [Nriver/Episode-ReName#31]
**问题描述**
在NAS上重命名文件，命令行窗口有正常输出，但是文件名实际并没有改变。

1. PC系统win10，NAS为绿联DX4600，使用samba协议访问NAS，并重命名已经下载完成的动画文件。
2. 命令行输出
![image](https://github.com/Nriver/Episode-ReName/assets/74303611/5a902d76-d161-4cbd-b62b-fd867c75d5d9)
![image](https://github.com/Nriver/Episode-ReName/assets/74303611/094e4d46-d896-490c-8af6-06444b1c3c63)
运行后：
![image](https://github.com/Nriver/Episode-ReName/assets/74303611/b3df45bf-41e9-482b-8c6a-bafa6a1e9f9d)

3.在本地测试发现功能是正常的，在NAS中也能够手动重命名。仔细查看路径发现输出的路径中\\UGREEN-E117\\cystathionine_使徒 的路径相比原始路径重复了两次。

**Comment by YumiGoo** [comment]
在本地测试发现功能是正常的，但是在NAS中也能够手动重命名。

**Comment by Nriver** [comment]
最新版已兼容samba路径，请更新

**Comment by YumiGoo** [comment]
感谢
