### ISSUE TITLE
[BUG反馈] name_format 与 all.txt冲突

### ISSUE THREAD

**Issue by Izumiko** [Nriver/Episode-ReName#33]
**问题描述**
当同时使用name_format 和 all.txt时，已经重命名的文件会被再次重命名，由于all.txt内容的存在，集数会反复累加，导致出错。

**复现步骤**
在执行脚本前，有如下文件夹结构：
```
Series/Season 1/{all.txt, name - 02.mp4, name - S01E01.mp4}
```
all.txt内容为-12，则在执行完带`--name_format "{series} - S{season}E{ep}"`参数的命令后，文件夹结构会变成
```
Series/Season 1/{all.txt, Series - S01E14.mp4, Series - S01E13.mp4}
```
实际应为
```
Series/Season 1/{all.txt, Series - S01E14.mp4, Series - S01E01.mp4}
```

看代码中，应该是有关标准化命名[相关的判定](https://github.com/Nriver/Episode-ReName/blob/e0861d0a7ef7d055ae4ef664b5b952ef088ddff6/EpisodeReName.py#L360)不太合适

**Comment by Izumiko** [comment]
另外，359和372行的正则感觉应该交换一下

**Comment by Nriver** [comment]
增加 name_format_bypass 参数，对满足 name_format 的文件跳过重命名。

359和372行的正则没有问题

**Comment by Izumiko** [comment]
发现[这里](https://github.com/Nriver/Episode-ReName/blob/e3ce4bc5ffc6ef650652ecaae380b79b2e534cc3/EpisodeReName.py#L736)的判断也要相应修一下。我说怎么最近每下一集新番，Jellyfin刮削的内容就没了

**Comment by Nriver** [comment]
没看懂什么问题，我不用jellyfin

**Comment by Izumiko** [comment]
Jellyfin会把刮削的结果存入与视频文件同名的nfo文件中，剧集的封面也是同名的jpg。在启用name_format的情况下，nfo和jpg的文件名会是`series SxxExx`格式，而736行的判断是`^S(\d{1,4})E(\d{1,4}(\.5)?)`，所以每次执行重命名时，会把Jellyfin以前的结果清空

**Comment by Nriver** [comment]
修改了一下判断的顺序
