### ISSUE TITLE
群晖套件版，第四步设置完后就无法做种了

### ISSUE THREAD

**Issue by liquidsnake9** [Nriver/Episode-ReName#35]
**问题描述**
群晖套件版qb

**复现步骤**
根据教程里的第四步，设置完，原本做种的任务全部就暂停了，再点继续，就无法继续做种了

**Comment by Nriver** [comment]
这个程序不是为做种设计的（~~下完就跑~~

**Comment by happyTonakai** [comment]
是否考虑建立硬链接的方式，这样qb还可以继续做种
