### ISSUE TITLE
无论怎么修改地址，始终提示没有关联的程序打开

### ISSUE THREAD

**Issue by xmcdlf1992** [Nriver/Episode-ReName#38]
Windows Registry Editor Version 5.00
[HKEY_CLASSES_ROOT\*\shell\EpisodeReName]
@="自动剧集命名"
"Icon"="C:\Users\mypc\Downloads\Episode-ReName-1.2.7.exe,0"

[HKEY_CLASSES_ROOT\*\shell\EpisodeReName\command]
@="C:\Users\mypc\Downloads\Episode-ReName-1.2.7.exe --path \"%1\" --overwrite 1"

[HKEY_CLASSES_ROOT\Directory\shell\EpisodeReName]
@="自动剧集命名"
"Icon"="C:\Users\mypc\Downloads\Episode-ReName-1.2.7.exe,0"

[HKEY_CLASSES_ROOT\Directory\shell\EpisodeReName\command]
@="C:\Users\mypc\Downloads\Episode-ReName-1.2.7.exe --path \"%1\" --overwrite 1"

无法使用，按照原始体例填写，依然提示没有关联程序

**Comment by xmcdlf1992** [comment]
尝试了删除双引号、删除“,0”，均无法生效

**Comment by Nriver** [comment]
注意斜杠 `C:\\Users\\mypc`

**Comment by xmcdlf1992** [comment]
是的，没想到是双斜杠
