### ISSUE TITLE
如何保留原來的影片名稱?

### ISSUE THREAD

**Issue by aaron0w0** [Nriver/Episode-ReName#41]
首先非常感謝你寫這個小程式，捐贈了小小的心意給你及保重身體!

如何可以保留原來的影片名稱? 如果很麻煩就算吧~現在這樣也可以。
例如 :
[Anime]  OVERTAKE! - 01 [1080P][AAC AVC].mkv
轉換為
[Anime]  OVERTAKE! - S0101 [1080P][AAC AVC].mkv

**Comment by Nriver** [comment]
十分感谢你的支持！我准备去买个红外线灯做理疗，可以减轻疼痛。

不过，你提到的功能我无法实现。这个程序设计上就是只能产出类似 S01E01.mp4 格式的文件，非常抱歉。
