### ISSUE TITLE
Linux系统下单文件重命名斜杠会出现问题

### ISSUE THREAD

**Issue by HalcyonAzure** [Nriver/Episode-ReName#5]
![image](https://user-images.githubusercontent.com/53591299/167126341-52a63203-7fca-4062-ba72-1836ac95a7b8.png)
如图，原路径为
```/data/theater/downloads/media/Animate/SPY×FAMILY/S1/[XKsub][SPY×FAMILY][02][CHS_JAP][1080P][WEBrip][MP4].mp4```
修改后路径为
```/data/theater/downloads/media/Animate/SPY×FAMILY/S1\\S01E02.mp4```

会导致在Linux环境下原本在`S1/abc.mp4`下的文件，变为和`S1`文件夹同级的文件，类似效果如下
![image](https://user-images.githubusercontent.com/53591299/167126683-07112c6f-68ac-4bf4-b460-86be40467188.png)

附：文件夹重命名不会出现该BUG，但是使用`qbittorrent`下载的过程中，如果其他文件没下载完，会将没下载完毕的文件一起重命名

**Comment by Nriver** [comment]
感谢PR，我没有针对linux仔细测试过。一开始准备在群晖上跑，后来各种原因还是做成windows优先了。

**Comment by HalcyonAzure** [comment]
顺便提供下我自己编译好，可以在我自用的x86平台[qbittorrent容器](https://hub.docker.com/r/johngong/qbittorrent)下使用的可执行文件。用的是[pyinstaller-alpine](https://github.com/six8/pyinstaller-alpine)这个容器里面的`python3.7`编译的。我自己没群晖，不过感觉应该群晖也能用。后面如果有遇到了平台兼容性问题也许能试试。（只能在Docker容器内运行，也就是`Alpine`环境下）

[EpisodeReName.zip](https://github.com/Nriver/Episode-ReName/files/8644661/EpisodeReName.zip)

配合`qbittorrent`按`README.md`就能正常使用单文件重命名了:satisfied:
![image](https://user-images.githubusercontent.com/53591299/167244099-3a0ae91d-a1dc-4567-9f73-6924e41ced85.png)
