### ISSUE TITLE
[BUG反馈]群晖套件版qb，因无loguru导致无法重命名

### ISSUE THREAD

**Issue by noir1216** [Nriver/Episode-ReName#50]
**问题描述**
群晖套件版qb，因无loguru导致无法重命名
发现最近下的番都没有自动重命名。看了下是因为1.2.9之后的版本path_utils.py加入了from loguru import logger项。
而群晖的python是没有loguru的。从而导致无法进行下一步。

**复现步骤**
1. 使用ssh登录群晖，执行代码。
2. 发现提示ModuleNotFoundError: No module named 'loguru'
3. 手动安装loguru之后正常使用

**截图**
![55555](https://github.com/Nriver/Episode-ReName/assets/44556349/6a6105d9-409d-46e1-a62f-28774db42fda)

希望作者在自述文件中更新下使用条件。

**Comment by Nriver** [comment]
感谢提醒，这是重构的问题，已做兼容修复
