### ISSUE TITLE
[BUG反馈]当有重复文件时，会导致后续文件重命名失败

### ISSUE THREAD

**Issue by noir1216** [Nriver/Episode-ReName#51]
**问题描述**
为了起到做种的目的，--delay设置的时间相对较长（1小时），所以Emby会先生成原始文件名对应的nfo文件
然后就当有重复文件时，会导致后续文件重命名失败。已使用 --overwrite 1 命令。

**复现步骤**
1. 用ssh连接NAS，把--delay时间为10，手动执行命令。
2. 报错信息：
`root@NAS:~# /usr/local/bin/python3 /var/packages/qBittorrent/target/ReName/EpisodeReName.py --path "/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1" --delay 10 --name_format "{series}-S{season}E{ep}" --overwrite 1`
`| INFO     | 文件夹处理`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/season.nfo')`
`| INFO     | 括号内未识别, 开始寻找括号外内容`
`| INFO     | pat \[.*?\]|\(.*?\)|【.*?】|「.*?」|\-|\_`
`| INFO     | 找末尾是数字的子字符串`
`| INFO     | ('01', None)`
`| INFO     | 未能识别`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [09][AVC-8bit 1080p AAC][CHS].nfo')`
`| INFO     | ('01', '09')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E09.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.mp4')`
`| INFO     | ('01', '01')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E01.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.nfo')`
`| INFO     | ('01', '01')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E01.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.mp4')`
`| INFO     | ('01', '02')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E02.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.nfo')`
`| INFO     | ('01', '02')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E02.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.mp4')`
`| INFO     | ('01', '03')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E03.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.nfo')`
`| INFO     | ('01', '03')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E03.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.mp4')`
`| INFO     | ('01', '04')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E04.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.nfo')`
`| INFO     | ('01', '04')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E04.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.mp4')`
`| INFO     | ('01', '05')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E05.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.nfo')`
`| INFO     | ('01', '05')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E05.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.mp4')`
`| INFO     | ('01', '06')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E06.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.nfo')`
`| INFO     | ('01', '06')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E06.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.mp4')`
`| INFO     | ('01', '07')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E07.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.nfo')`
`| INFO     | ('01', '07')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E07.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.mp4')`
`| INFO     | ('01', '08')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E08.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.nfo')`
`| INFO     | ('01', '08')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E08.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.mp4')`
`| INFO     | ('01', '09')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E09.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.nfo')`
`| INFO     | ('01', '09')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E09.nfo`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [10][AVC-8bit 1080p AAC][CHS].mp4')`
`| INFO     | ('01', '10')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E10.mp4`
`| INFO     | ('解析文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [10][AVC-8bit 1080p AAC][CHS].nfo')`
`| INFO     | ('01', '10')`
`| INFO     | 狼与香辛料 行商邂逅贤狼-S01E10.nfo`
`| INFO     | ----- 未识别文件 -----`
`| INFO     | /volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/season.nfo`
`| INFO     | 重命名延迟等待中...`
`| INFO     | ('file_lists', [['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [09][AVC-8bit 1080p AAC][CHS].nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E01.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E02.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E03.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E04.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E05.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E06.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E07.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E08.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.nfo'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [10][AVC-8bit 1080p AAC][CHS].mp4', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E10.mp4'], ['/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/[Sakurato] Ookami to Koushinryou：Merchant Meets the Wise Wolf [10][AVC-8bit 1080p AAC][CHS].nfo', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E10.nfo']])`
`| WARNING  | 旧文件数量和新文件数量不一致，可能会被覆盖。请检查文件命名`
`| WARNING  | ('重复文件', '/volume2/视频/动漫/2024年4月新番/狼与香辛料 行商邂逅贤狼/S1/狼与香辛料 行商邂逅贤狼-S01E09.nfo')`

**Comment by Nriver** [comment]
要么手动删文件, 要么关掉emby的削刮.

**Comment by noir1216** [comment]
> 要么手动删文件, 要么关掉emby的削刮.

代码无法做到重命名时遇到同名文件强制覆盖吗
看来只能手动删除了 (ಥ﹏ಥ)
