### ISSUE TITLE
[BUG反馈]

### ISSUE THREAD

**Issue by Super-Passerby** [Nriver/Episode-ReName#52]
**问题描述**
请简要描述你遇到的问题.

在重命名 28(1).mp4、29(2).mp4 这样的文件时，重名命名后分别会变成：S01E01、S01E02；

实际分别应为：S01E28、S01E29

**Comment by Nriver** [comment]
不是正常命名, 不处理这种情况.

**Comment by Nriver** [comment]
或者你可以设置偏移量参数

**Comment by Nriver** [comment]
参考 https://github.com/Nriver/Episode-ReName?tab=readme-ov-file#-%E5%A4%9A%E5%AD%A3%E7%95%AA%E5%89%A7tmdb%E9%9B%86%E6%95%B0%E9%80%82%E9%85%8D

你的情况就是新建一个all.txt, 里面写上 `-27`
