### ISSUE TITLE
重命名字幕文件后文件消失

### ISSUE THREAD

**Issue by MNGDT** [Nriver/Episode-ReName#53]
在同时重命名3种不同语言字幕文件后只剩下一种语言的字幕文件
重命名前：
![1d85367a-7d1b-4b48-99cd-0c95abb5849a](https://github.com/user-attachments/assets/32907e02-ddc2-4b4f-9ede-a0d5077a4d5b)
重命名后：
![7d2e6a0a-3442-412d-b02a-ea8d226f274e](https://github.com/user-attachments/assets/d50a74ee-d6c1-46a6-b133-5252600ffd1d)

**Comment by Nriver** [comment]
最新版已兼容这种格式，请更新

**Comment by MNGDT** [comment]
好的，幸苦了
