### ISSUE TITLE
[BUG反馈] linuxserver/qbittorrent:latest; 因无loguru导致无法重命名

### ISSUE THREAD

**Issue by xyyandxyy** [Nriver/Episode-ReName#55]
**问题描述**
qBittorrent v4.6.5, 使用容器自带的python, 因无loguru导致无法重命名

**截图**
![issue](https://github.com/user-attachments/assets/2385629d-b8f5-48f8-aa22-84df7307945d)

**Comment by Nriver** [comment]
修复了，更新一下代码

**Comment by xyyandxyy** [comment]
可以了, 谢谢大佬
