### ISSUE TITLE
[BUG反馈] linuxserver/qbittorrent:latest; 容器内部文件夹权限有问题, 无法重命名

### ISSUE THREAD

**Issue by xyyandxyy** [Nriver/Episode-ReName#56]
**问题描述**
qBittorrent v4.6.5, 使用容器自带的python.

1. 发现有时候下种子报错: `文件错误警报。Torrent：“[KitaujiSub] Make Heroine ga Oosugiru! [08][WebRip][HEVC_AAC][CHS_JP&CHT_JP].mkv”。文件：“/media/shows/败犬/S01/[KitaujiSub] Make Heroine ga Oosugiru! [08][WebRip][HEVC_AAC][CHS_JP&CHT_JP].mkv”。原因：“[KitaujiSub] Make Heroine ga Oosugiru! [08][WebRip][HEVC_AAC][CHS_JP&CHT_JP].mkv file_open (/media/shows/败犬/S01/[KitaujiSub] Make Heroine ga Oosugiru! [08][WebRip][HEVC_AAC][CHS_JP&CHT_JP].mkv) error: Permission denied”`
1. 将对应文件夹权限手动`chmod 777 DIRECTORY`后即正常下载.

不确定是否是因为之前在容器内手动执行过repo中的Python文件, 导致和自动执行时的用户不一样(?不确定), 权限不对应导致的.
建议可以考虑增加一个重写权限的功能

**Comment by Nriver** [comment]
权限问题是你的docker配置问题，和重命名工具无关，也不应该由重命名来处理。
