### ISSUE TITLE
部份字幕组会在一季的最后一集带上end

### ISSUE THREAD

**Issue by shelken** [Nriver/Episode-ReName#8]
如下：
![DF0F3E9C-239B-43BD-9B5B-5237344FB165](https://user-images.githubusercontent.com/33972006/171000531-764b66cb-b566-445f-8dd5-3670706dc45b.jpeg)
![057EEC27-DBA5-4A68-9731-6196AEA46801](https://user-images.githubusercontent.com/33972006/171000536-ad59a3fa-ebd5-4a8f-81ad-1cbfd9a5181d.jpeg)
希望能适配这种情况，谢谢大佬

**Comment by Nriver** [comment]
最新版已兼容end格式

**Comment by shelken** [comment]
> 

感谢大佬
